Update appDeploy.yml

diff --git a/.github/workflows/appDeploy.yml b/.github/workflows/appDeploy.yml
--- a/.github/workflows/appDeploy.yml
+++ b/.github/workflows/appDeploy.yml
@@ -66,6 +66,8 @@ jobs:
           checksum=$(shasum -a 256 "$file_path" | awk '{ print $1 }')
           echo "checksum=$checksum" >> $GITHUB_ENV
 
+      # Other steps remain the same
+      
       - name: Create Screenshot Set
         id: create_screenshot_set
         run: |
@@ -89,10 +91,17 @@ jobs:
               }
             }' \
             https://api.appstoreconnect.apple.com/v1/appScreenshotSets)
-
+      
+          echo "Create Screenshot Set Response: $response"
           screenshot_set_id=$(echo $response | jq -r '.data.id')
+      
+          if [ "$screenshot_set_id" == "null" ] || [ -z "$screenshot_set_id" ]; then
+            echo "Failed to create screenshot set or invalid screenshot_set_id."
+            exit 1
+          fi
+      
           echo "screenshot_set_id=$screenshot_set_id" >> $GITHUB_ENV
-
+      
       - name: Upload Screenshot
         run: |
           response=$(curl -X POST \
@@ -116,26 +125,16 @@ jobs:
               }
             }' \
             https://api.appstoreconnect.apple.com/v1/appScreenshots)
-
+      
+          echo "Upload Screenshot Response: $response"
           upload_url=$(echo $response | jq -r '.data.attributes.uploadOperations[0].url')
+      
+          if [ -z "$upload_url" ]; then
+            echo "Failed to obtain upload URL."
+            exit 1
+          fi
+      
           curl -X PUT \
             -H "Content-Type: image/png" \
             --data-binary "@src/assets/Screenshots/04.png" \
             "$upload_url"
-
-      - name: Finalize Screenshot Upload
-        run: |
-          screenshot_id=$(echo $response | jq -r '.data.id')
-          curl -X PATCH \
-            -H "Authorization: Bearer ${{ secrets.token }}" \
-            -H "Content-Type: application/json" \
-            -d '{
-              "data": {
-                "id": "'"$screenshot_id"'",
-                "type": "appScreenshots",
-                "attributes": {
-                  "uploaded": true
-                }
-              }
-            }' \
-            https://api.appstoreconnect.apple.com/v1/appScreenshots/"$screenshot_id"
