Update appDeploy.yml

diff --git a/.github/workflows/appDeploy.yml b/.github/workflows/appDeploy.yml
--- a/.github/workflows/appDeploy.yml
+++ b/.github/workflows/appDeploy.yml
@@ -81,23 +81,42 @@ jobs:
           echo "token=$token" >> $GITHUB_ENV
 
 
+      # - name: Get App ID
+      #   id: get_app_id
+      #   run: |
+      #     bundle_id="${{ env.BUNDLE_IDentifier }}"  
+      
+      #     response=$(curl -X GET \
+      #       -H "Authorization: Bearer ${{ env.token }}" \
+      #       "https://api.appstoreconnect.apple.com/v1/apps?filter%5BbundleId%5D=$bundle_id")
+      
+      #     echo "Response: $response"
+      
+      #     app_id=$(echo $response | jq -r '.data[0].id')
+      
+      #     if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
+      #       echo "Failed to retrieve app ID."
+      #       exit 1
+      #     fi
+
       - name: Get App ID
         id: get_app_id
         run: |
-          bundle_id="${{ env.BUNDLE_IDentifier }}"  # Replace with your app's Bundle ID
-      
           response=$(curl -X GET \
             -H "Authorization: Bearer ${{ env.token }}" \
-            "https://api.appstoreconnect.apple.com/v1/apps?filter%5BbundleId%5D=$bundle_id")
+            "https://api.appstoreconnect.apple.com/v1/apps")
       
-          echo "Response: $response"
+          echo "Full API Response: $response"
       
-          app_id=$(echo $response | jq -r '.data[0].id')
+          app_id=$(echo $response | jq -r '.data[] | select(.attributes.bundleId=="'${{ env.BUNDLE_IDentifier }}'") | .id')
       
           if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
             echo "Failed to retrieve app ID."
             exit 1
+          else
+            echo "App ID: $app_id"
           fi
+
       
       #     echo "app_id=$app_id" >> $GITHUB_ENV
 
