Update appDeploy.yml

diff --git a/.github/workflows/appDeploy.yml b/.github/workflows/appDeploy.yml
--- a/.github/workflows/appDeploy.yml
+++ b/.github/workflows/appDeploy.yml
@@ -118,149 +118,149 @@ jobs:
           fi
 
       
-      #     echo "app_id=$app_id" >> $GITHUB_ENV
+          echo "app_id=$app_id" >> $GITHUB_ENV
 
-      # - name: Get App Store Version ID
-      #   id: get_app_store_version_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
+      - name: Get App Store Version ID
+        id: get_app_store_version_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
+          app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
       
-      #     if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
-      #       echo "Failed to retrieve app store version ID."
-      #       exit 1
-      #     fi
+          if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
+            echo "Failed to retrieve app store version ID."
+            exit 1
+          fi
       
-      #     echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
+          echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
 
-      # - name: Get App Store Version Localization ID
-      #   id: get_app_store_version_localization_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
+      - name: Get App Store Version Localization ID
+        id: get_app_store_version_localization_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
+          app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
       
-      #     if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
-      #       echo "Failed to retrieve app store version localization ID."
-      #       exit 1
-      #     fi
+          if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
+            echo "Failed to retrieve app store version localization ID."
+            exit 1
+          fi
       
-      #     echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
+          echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
 
-      # - name: Update App Store Version Localization
-      #   id: update_app_store_version_localization
-      #   run: |
-      #     response=$(curl -X PATCH \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       -H "Content-Type: application/json" \
-      #       -d '{
-      #         "data": {
-      #           "id": "'${{ env.app_store_version_localization_id }}'",
-      #           "type": "appStoreVersionLocalizations",
-      #           "attributes": {
-      #             "description": "here goes your app description...",
-      #             "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
-      #             "marketingUrl": null,
-      #             "promotionalText": "We introduce new features and improvements to improve your experience",
-      #             "supportUrl": "https://easy-health.app/landing-page/index.html"
-      #           }
-      #         }
-      #       }' \
-      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
+      - name: Update App Store Version Localization
+        id: update_app_store_version_localization
+        run: |
+          response=$(curl -X PATCH \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "data": {
+                "id": "'${{ env.app_store_version_localization_id }}'",
+                "type": "appStoreVersionLocalizations",
+                "attributes": {
+                  "description": "here goes your app description...",
+                  "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
+                  "marketingUrl": null,
+                  "promotionalText": "We introduce new features and improvements to improve your experience",
+                  "supportUrl": "https://easy-health.app/landing-page/index.html"
+                }
+              }
+            }' \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
           
-      #     echo "Update App Store Version Localization Response: $response"
+          echo "Update App Store Version Localization Response: $response"
 
 
-      # - name: Create Screenshot Set
-      #   id: create_screenshot_set
-      #   run: |
-      #     response=$(curl -X POST \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       -H "Content-Type: application/json" \
-      #       -d '{
-      #         "data": {
-      #           "type": "appScreenshotSets",
-      #           "attributes": {
-      #             "screenshotDisplayType": "APP_IPHONE_65"
-      #           },
-      #           "relationships": {
-      #             "appStoreVersionLocalization": {
-      #               "data": {
-      #                 "id": "'${{ env.app_store_version_localization_id }}'",
-      #                 "type": "appStoreVersionLocalizations"
-      #               }
-      #             }
-      #           }
-      #         }
-      #       }' \
-      #       https://api.appstoreconnect.apple.com/v1/appScreenshotSets)
+      - name: Create Screenshot Set
+        id: create_screenshot_set
+        run: |
+          response=$(curl -X POST \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "data": {
+                "type": "appScreenshotSets",
+                "attributes": {
+                  "screenshotDisplayType": "APP_IPHONE_65"
+                },
+                "relationships": {
+                  "appStoreVersionLocalization": {
+                    "data": {
+                      "id": "'${{ env.app_store_version_localization_id }}'",
+                      "type": "appStoreVersionLocalizations"
+                    }
+                  }
+                }
+              }
+            }' \
+            https://api.appstoreconnect.apple.com/v1/appScreenshotSets)
 
-      #     echo "Create Screenshot Set Response: $response"
+          echo "Create Screenshot Set Response: $response"
 
-      #     screenshot_set_id=$(echo $response | jq -r '.data.id')
+          screenshot_set_id=$(echo $response | jq -r '.data.id')
 
-      #     if [ "$screenshot_set_id" == "null" ] || [ -z "$screenshot_set_id" ]; then
-      #       echo "Failed to create screenshot set or invalid screenshot_set_id."
-      #       exit 1
-      #     fi
+          if [ "$screenshot_set_id" == "null" ] || [ -z "$screenshot_set_id" ]; then
+            echo "Failed to create screenshot set or invalid screenshot_set_id."
+            exit 1
+          fi
 
-      #     echo "screenshot_set_id=$screenshot_set_id" >> $GITHUB_ENV
+          echo "screenshot_set_id=$screenshot_set_id" >> $GITHUB_ENV
 
-      # - name: Upload Screenshot
-      #   run: |
-      #     file_path="src/assets/Screenshots/04.png"
-      #     file_name=$(basename "$file_path")
-      #     file_size=$(stat -f%z "$file_path")
+      - name: Upload Screenshot
+        run: |
+          file_path="src/assets/Screenshots/04.png"
+          file_name=$(basename "$file_path")
+          file_size=$(stat -f%z "$file_path")
       
-      #     response=$(curl -X POST \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       -H "Content-Type: application/json" \
-      #       -d '{
-      #         "data": {
-      #           "type": "appScreenshots",
-      #           "attributes": {
-      #             "fileName": "'$file_name'",
-      #             "fileSize": '$file_size'
-      #           },
-      #           "relationships": {
-      #             "appScreenshotSet": {
-      #               "data": {
-      #                 "id": "ee94f55b-3af8-49c7-806b-3ef5475a5292",
-      #                 "type": "appScreenshotSets"
-      #               }
-      #             }
-      #           }
-      #         }
-      #       }' \
-      #       https://api.appstoreconnect.apple.com/v1/appScreenshots)
+          response=$(curl -X POST \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "data": {
+                "type": "appScreenshots",
+                "attributes": {
+                  "fileName": "'$file_name'",
+                  "fileSize": '$file_size'
+                },
+                "relationships": {
+                  "appScreenshotSet": {
+                    "data": {
+                      "id": "ee94f55b-3af8-49c7-806b-3ef5475a5292",
+                      "type": "appScreenshotSets"
+                    }
+                  }
+                }
+              }
+            }' \
+            https://api.appstoreconnect.apple.com/v1/appScreenshots)
       
-      #     echo "Create Screenshot Response: $response"
+          echo "Create Screenshot Response: $response"
       
-      #     upload_url=$(echo $response | jq -r '.data.attributes.uploadOperations[0].url')
+          upload_url=$(echo $response | jq -r '.data.attributes.uploadOperations[0].url')
       
-      #     if [ "$upload_url" == "null" ] || [ -z "$upload_url" ]; then
-      #       echo "Failed to retrieve upload URL."
-      #       exit 1
-      #     fi
+          if [ "$upload_url" == "null" ] || [ -z "$upload_url" ]; then
+            echo "Failed to retrieve upload URL."
+            exit 1
+          fi
       
-      #     curl -X PUT \
-      #       -H "Content-Type: image/png" \
-      #       --data-binary "@$file_path" \
-      #       "$upload_url"
+          curl -X PUT \
+            -H "Content-Type: image/png" \
+            --data-binary "@$file_path" \
+            "$upload_url"
       
-      #     if [ $? -ne 0 ]; then
-      #       echo "Failed to upload screenshot."
-      #       exit 1
-      #     fi
+          if [ $? -ne 0 ]; then
+            echo "Failed to upload screenshot."
+            exit 1
+          fi
 
 
 
