Update appDeploy.yml

diff --git a/.github/workflows/appDeploy.yml b/.github/workflows/appDeploy.yml
--- a/.github/workflows/appDeploy.yml
+++ b/.github/workflows/appDeploy.yml
@@ -120,54 +120,40 @@ jobs:
 
 
 
-      - name: Check for Existing Screenshot Set
-        id: check_screenshot_set
-        run: |
-          response=$(curl -X GET \
-            -H "Authorization: Bearer ${{ env.token }}" \
-            "https://api.appstoreconnect.apple.com/v1/appScreenshotSets?filter%5BappStoreVersionLocalization%5D=${{ env.app_store_version_localization_id }}")
-      
-          echo "Check Screenshot Set Response: $response"
-      
-          screenshot_set_id=$(echo $response | jq -r '.data[0].id')
-      
-          if [ "$screenshot_set_id" == "null" ] || [ -z "$screenshot_set_id" ]; then
-            echo "No existing screenshot set found, creating a new one."
-      
-            response=$(curl -X POST \
-              -H "Authorization: Bearer ${{ env.token }}" \
-              -H "Content-Type: application/json" \
-              -d '{
-                "data": {
-                  "type": "appScreenshotSets",
-                  "attributes": {
-                    "screenshotDisplayType": "APP_IPHONE_65"
-                  },
-                  "relationships": {
-                    "appStoreVersionLocalization": {
-                      "data": {
-                        "id": "'${{ env.app_store_version_localization_id }}'",
-                        "type": "appStoreVersionLocalizations"
-                      }
-                    }
-                  }
-                }
-              }' \
-              https://api.appstoreconnect.apple.com/v1/appScreenshotSets)
-      
-            echo "Create Screenshot Set Response: $response"
-      
-            screenshot_set_id=$(echo $response | jq -r '.data.id')
-      
-            if [ "$screenshot_set_id" == "null" ] || [ -z "$screenshot_set_id" ]; then
-              echo "Failed to create screenshot set or invalid screenshot_set_id."
-              exit 1
-            fi
-          else
-            echo "Existing screenshot set found."
-          fi
-      
-          echo "screenshot_set_id=$screenshot_set_id" >> $GITHUB_ENV
+      # - name: Create Screenshot Set
+      #   id: create_screenshot_set
+      #   run: |
+      #     response=$(curl -X POST \
+      #       -H "Authorization: Bearer ${{ env.token }}" \
+      #       -H "Content-Type: application/json" \
+      #       -d '{
+      #         "data": {
+      #           "type": "appScreenshotSets",
+      #           "attributes": {
+      #             "screenshotDisplayType": "APP_IPHONE_65"
+      #           },
+      #           "relationships": {
+      #             "appStoreVersionLocalization": {
+      #               "data": {
+      #                 "id": "'${{ env.app_store_version_localization_id }}'",
+      #                 "type": "appStoreVersionLocalizations"
+      #               }
+      #             }
+      #           }
+      #         }
+      #       }' \
+      #       https://api.appstoreconnect.apple.com/v1/appScreenshotSets)
+
+      #     echo "Create Screenshot Set Response: $response"
+
+      #     screenshot_set_id=$(echo $response | jq -r '.data.id')
+
+      #     if [ "$screenshot_set_id" == "null" ] || [ -z "$screenshot_set_id" ]; then
+      #       echo "Failed to create screenshot set or invalid screenshot_set_id."
+      #       exit 1
+      #     fi
+
+      #     echo "screenshot_set_id=$screenshot_set_id" >> $GITHUB_ENV
       
       - name: Upload Screenshot
         run: |
@@ -188,7 +174,7 @@ jobs:
                 "relationships": {
                   "appScreenshotSet": {
                     "data": {
-                      "id": "'${{ env.screenshot_set_id }}'",
+                      "id": "ee94f55b-3af8-49c7-806b-3ef5475a5292",
                       "type": "appScreenshotSets"
                     }
                   }
