Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -472,57 +472,145 @@ jobs:
           </plist>
           EOF
 
+        # *************************************** Prerequisetries End ********************************************
 
+
+      # ******************************************* Uploading Meta Data **************************************
+
+      - name: Get App ID
+        id: get_app_id
+        run: |
+          bundle_id="com.org.easyPatientTesting3"  # Replace with your app's Bundle ID
+      
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps?filter%5BbundleId%5D=$bundle_id")
+      
+          echo "Response: $response"
+      
+          app_id=$(echo $response | jq -r '.data[0].id')
+      
+          if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
+            echo "Failed to retrieve app ID."
+            exit 1
+          fi
+      
+          echo "app_id=$app_id" >> $GITHUB_ENV
+
+      - name: Get App Store Version ID
+        id: get_app_store_version_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
+      
+          echo "Response: $response"
+      
+          app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
+      
+          if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
+            echo "Failed to retrieve app store version ID."
+            exit 1
+          fi
+      
+          echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
+
+      - name: Get App Store Version Localization ID
+        id: get_app_store_version_localization_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
+      
+          echo "Response: $response"
+      
+          app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
+      
+          if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
+            echo "Failed to retrieve app store version localization ID."
+            exit 1
+          fi
+      
+          echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
+
+      - name: Update App Store Version Localization
+        id: update_app_store_version_localization
+        run: |
+          response=$(curl -X PATCH \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "data": {
+                "id": "'${{ env.app_store_version_localization_id }}'",
+                "type": "appStoreVersionLocalizations",
+                "attributes": {
+                  "description": "here goes your app description...",
+                  "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
+                  "marketingUrl": null,
+                  "promotionalText": "We introduce new features and improvements to improve your experience",
+                  "supportUrl": "https://easy-health.app/landing-page/index.html"
+                }
+              }
+            }' \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
+          
+          echo "Update App Store Version Localization Response: $response"
+
+
+       # ******************************************* Uploading Meta Data END **************************************
+
+
+      # *************************************** Build Start ******************************************************
   
 
-      - name: Install CocoaPods
-        run: gem install cocoapods
+      # - name: Install CocoaPods
+      #   run: gem install cocoapods
 
-      - name: Cache CocoaPods
-        uses: actions/cache@v3
-        with:
-          path: ios/Pods
-          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-pods-
+      # - name: Cache CocoaPods
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ios/Pods
+      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-pods-
 
-      - name: Install Node.js dependencies
-        run: npm install --force
+      # - name: Install Node.js dependencies
+      #   run: npm install --force
 
-      - name: Install Pods
-        run: |
-          cd ios
-          pod deintegrate
-          rm -rf Pods Podfile.lock
-          pod update
-          pod install
+      # - name: Install Pods
+      #   run: |
+      #     cd ios
+      #     pod deintegrate
+      #     rm -rf Pods Podfile.lock
+      #     pod update
+      #     pod install
 
-      - name: Install Xcode 15.3
-        run: |
-          sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
-          xcodebuild -version
+      # - name: Install Xcode 15.3
+      #   run: |
+      #     sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
+      #     xcodebuild -version
 
-      - name: Clean Derived Data
-        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
+      # - name: Clean Derived Data
+      #   run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
 
      
-      - name: Clean Build Folder
-        run: |
-          cd ios
-          xcodebuild clean -workspace EasyPatientDynamic.xcworkspace -scheme EasyPatientDynamic -configuration Release
+      # - name: Clean Build Folder
+      #   run: |
+      #     cd ios
+      #     xcodebuild clean -workspace EasyPatientDynamic.xcworkspace -scheme EasyPatientDynamic -configuration Release
 
-      - name: Build Archive
-        run: |
-          xcodebuild clean archive \
-            -workspace ios/EasyPatientDynamic.xcworkspace \
-            -scheme EasyPatientDynamic \
-            -sdk iphoneos \
-            -destination generic/platform=iOS \
-            -configuration Release \
-            -derivedDataPath ios/build/DerivedData \
-            -archivePath ios/build/archive/TestingArchive.xcarchive \
-            PROVISIONING_PROFILE_SPECIFIER="MyApp Distribution Profile 9" \
-            CODE_SIGN_IDENTITY="${CERTIFICATE_NAME}"
+      # - name: Build Archive
+      #   run: |
+      #     xcodebuild clean archive \
+      #       -workspace ios/EasyPatientDynamic.xcworkspace \
+      #       -scheme EasyPatientDynamic \
+      #       -sdk iphoneos \
+      #       -destination generic/platform=iOS \
+      #       -configuration Release \
+      #       -derivedDataPath ios/build/DerivedData \
+      #       -archivePath ios/build/archive/TestingArchive.xcarchive \
+      #       PROVISIONING_PROFILE_SPECIFIER="MyApp Distribution Profile 9" \
+      #       CODE_SIGN_IDENTITY="${CERTIFICATE_NAME}"
 
 
 
