Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -694,57 +694,70 @@ jobs:
           response=$(curl -X GET \
             -H "Authorization: Bearer ${{ env.token }}" \
             "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
-      
+          
           echo "Response: $response"
-      
-          app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
-      
+          
+          # Assuming you want the first version
+          app_store_version_id=$(echo $response | jq -r '.data[0].id')
+          
           if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
             echo "Failed to retrieve app store version ID."
             exit 1
           fi
-      
+          
           echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
-
+      
+      - name: Get App Store Version Localization ID
+        id: get_app_store_version_localization_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
+          
+          echo "Response: $response"
+          
+          # Assuming you want the first localization (adjust as needed)
+          app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')
+          
+          if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
+            echo "Failed to retrieve app store version localization ID."
+            exit 1
+          fi
+          
+          echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
+      
       - name: Update App Store Version Localization
         id: update_app_store_version_localization
         run: |
           # Initialize the payload with required attributes
-          payload=$(cat <<EOF
-          {
-            "data": {
-              "id": "${{ env.app_store_version_localization_id }}",
-              "type": "appStoreVersionLocalizations",
-              "attributes": {
-                "description": "${{ env.DESCRIPTION }}",
-                "keywords": "${{ env.KEYWORDS }}",
-                "promotionalText": "${{ env.PROMOTIONAL_TEXT }}"
-          EOF
-              )
+          payload=$(jq -n --arg id "${{ env.app_store_version_localization_id }}" \
+                          --arg type "appStoreVersionLocalizations" \
+                          --arg description "${{ env.DESCRIPTION }}" \
+                          --arg keywords "${{ env.KEYWORDS }}" \
+                          --arg promotionalText "${{ env.PROMOTIONAL_TEXT }}" \
+                          '{
+                            data: {
+                              id: $id,
+                              type: $type,
+                              attributes: {
+                                description: $description,
+                                keywords: $keywords,
+                                promotionalText: $promotionalText
+                              }
+                            }
+                          }')
           
-              # Conditionally add marketingUrl if it's defined
-              if [ -n "${{ env.MARKETING_URL }}" ]; then
-                payload=$(echo "$payload,"$(cat <<EOF
-                "marketingUrl": "${{ env.MARKETING_URL }}"
-          EOF
-                ))
-              fi
-          
-              # Conditionally add supportUrl if it's defined
-              if [ -n "${{ env.SUPPORT_URL }}" ]; then
-                payload=$(echo "$payload,"$(cat <<EOF
-                "supportUrl": "${{ env.SUPPORT_URL }}"
-          EOF
-                ))
-              fi
-          
-              # Close the JSON payload
-              payload=$(echo "$payload"$(cat <<EOF
-              }
-            }
-          }
-          EOF
-          ))
+          # Conditionally add marketingUrl if it's defined
+          if [ -n "${{ env.MARKETING_URL }}" ]; then
+            payload=$(echo "$payload" | jq --arg marketingUrl "${{ env.MARKETING_URL }}" \
+                                           '.data.attributes.marketingUrl = $marketingUrl')
+          fi
+      
+          # Conditionally add supportUrl if it's defined
+          if [ -n "${{ env.SUPPORT_URL }}" ]; then
+            payload=$(echo "$payload" | jq --arg supportUrl "${{ env.SUPPORT_URL }}" \
+                                           '.data.attributes.supportUrl = $supportUrl')
+          fi
       
           # Debugging to verify payload
           echo "Payload: $payload"
@@ -767,86 +780,86 @@ jobs:
       # *************************************** Build Start ******************************************************
   
 
-      - name: Install CocoaPods
-        run: gem install cocoapods
+      # - name: Install CocoaPods
+      #   run: gem install cocoapods
 
-      - name: Cache CocoaPods
-        uses: actions/cache@v3
-        with:
-          path: ios/Pods
-          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-pods-
+      # - name: Cache CocoaPods
+      #   uses: actions/cache@v3
+      #   with:
+      #     path: ios/Pods
+      #     key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-pods-
 
-      - name: Install Node.js dependencies
-        run: npm install --force
+      # - name: Install Node.js dependencies
+      #   run: npm install --force
 
-      - name: Install Pods
-        run: |
-          cd ios
-          pod deintegrate
-          rm -rf Pods Podfile.lock
-          pod update
-          pod install
+      # - name: Install Pods
+      #   run: |
+      #     cd ios
+      #     pod deintegrate
+      #     rm -rf Pods Podfile.lock
+      #     pod update
+      #     pod install
 
-      - name: Install Xcode 15.3
-        run: |
-          sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
-          xcodebuild -version
+      # - name: Install Xcode 15.3
+      #   run: |
+      #     sudo xcode-select -s /Applications/Xcode_15.3.app/Contents/Developer
+      #     xcodebuild -version
 
-      - name: Clean Derived Data
-        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
+      # - name: Clean Derived Data
+      #   run: rm -rf ~/Library/Developer/Xcode/DerivedData/*
 
      
-      - name: Clean Build Folder
-        run: |
-          cd ios
-          xcodebuild clean -workspace EasyPatientDynamic.xcworkspace -scheme EasyPatientDynamic -configuration Release
+      # - name: Clean Build Folder
+      #   run: |
+      #     cd ios
+      #     xcodebuild clean -workspace EasyPatientDynamic.xcworkspace -scheme EasyPatientDynamic -configuration Release
 
-      - name: Build Archive
-        run: |
-          echo "PRODUCT_BUNDLE_IDENTIFIER is: ${{ env.BUNDLE_IDentifier }}"
-          xcodebuild clean archive \
-            -workspace ios/EasyPatientDynamic.xcworkspace \
-            -scheme EasyPatientDynamic \
-            -sdk iphoneos \
-            -destination generic/platform=iOS \
-            -configuration Release \
-            -derivedDataPath ios/build/DerivedData \
-            -archivePath ios/build/archive/TestingArchive.xcarchive \
-            PROVISIONING_PROFILE_SPECIFIER="MyApp Distribution Profile 17" \
-            CODE_SIGN_IDENTITY="${{ env.CERTIFICATE_NAME }}" \
-            DEVELOPMENT_TEAM="${{ env.TEAM_ID }}" \
-            PRODUCT_BUNDLE_IDENTIFIER="${{ env.BUNDLE_IDentifier }}"
+      # - name: Build Archive
+      #   run: |
+      #     echo "PRODUCT_BUNDLE_IDENTIFIER is: ${{ env.BUNDLE_IDentifier }}"
+      #     xcodebuild clean archive \
+      #       -workspace ios/EasyPatientDynamic.xcworkspace \
+      #       -scheme EasyPatientDynamic \
+      #       -sdk iphoneos \
+      #       -destination generic/platform=iOS \
+      #       -configuration Release \
+      #       -derivedDataPath ios/build/DerivedData \
+      #       -archivePath ios/build/archive/TestingArchive.xcarchive \
+      #       PROVISIONING_PROFILE_SPECIFIER="MyApp Distribution Profile 17" \
+      #       CODE_SIGN_IDENTITY="${{ env.CERTIFICATE_NAME }}" \
+      #       DEVELOPMENT_TEAM="${{ env.TEAM_ID }}" \
+      #       PRODUCT_BUNDLE_IDENTIFIER="${{ env.BUNDLE_IDentifier }}"
 
 
-      - name: Export IPA
-        run: |
-          xcodebuild -exportArchive \
-            -archivePath ios/build/archive/TestingArchive.xcarchive \
-            -exportOptionsPlist ios/ExportOptions.plist \
-            -exportPath ios/build/archive/TestingIPA
+      # - name: Export IPA
+      #   run: |
+      #     xcodebuild -exportArchive \
+      #       -archivePath ios/build/archive/TestingArchive.xcarchive \
+      #       -exportOptionsPlist ios/ExportOptions.plist \
+      #       -exportPath ios/build/archive/TestingIPA
       
-      - name: Upload IPA as Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: TestingIPA
-          path: ios/build/archive/TestingIPA/*.ipa
+      # - name: Upload IPA as Artifact
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: TestingIPA
+      #     path: ios/build/archive/TestingIPA/*.ipa
 
 
 
-      - name: Find IPA file
-        id: find_ipa
-        run: |
-          ipa_path=$(find ios/build/archive/TestingIPA -name "*.ipa" | head -n 1)
-          echo "IPA_PATH=$ipa_path" >> $GITHUB_ENV
+      # - name: Find IPA file
+      #   id: find_ipa
+      #   run: |
+      #     ipa_path=$(find ios/build/archive/TestingIPA -name "*.ipa" | head -n 1)
+      #     echo "IPA_PATH=$ipa_path" >> $GITHUB_ENV
       
-      - name: Upload IPA to App Store Connect
-        run: |
-          xcrun altool --upload-app -f "${{ env.IPA_PATH }}" \
-            -t ios \
-            --apiKey ${{ env.KEY_ID }} \
-            --apiIssuer ${{ env.ISSUER_ID }} \
+      # - name: Upload IPA to App Store Connect
+      #   run: |
+      #     xcrun altool --upload-app -f "${{ env.IPA_PATH }}" \
+      #       -t ios \
+      #       --apiKey ${{ env.KEY_ID }} \
+      #       --apiIssuer ${{ env.ISSUER_ID }} \
 
  
 
