Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -414,7 +414,7 @@ jobs:
         run: |
           echo "Creating Distribution Provisioning Profile..."
           
-          PROFILE_NAME="MyApp Distribution Profile 13"  
+          PROFILE_NAME="MyApp Distribution Profile 14"  
           BUNDLE_ID="${BUNDLE_ID}"
           CERTIFICATE_ID="${{ env.CERTIFICATE_ID }}"  
           
@@ -465,7 +465,7 @@ jobs:
           mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
           
           # Decode the Base64 content and save it as a .mobileprovision file
-          echo "$profile_content" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/MyApp_Distribution_Profile_13.mobileprovision
+          echo "$profile_content" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/MyApp_Distribution_Profile_14.mobileprovision
 
       - name: Create ExportOptions.plist
         run: |
@@ -481,7 +481,7 @@ jobs:
               <key>provisioningProfiles</key>
               <dict>
                   <key>${{ env.BUNDLE_IDentifier }}</key> <!-- Replace with your actual Bundle Identifier -->
-                  <string>MyApp Distribution Profile 12</string> <!-- Replace with your Provisioning Profile Name -->
+                  <string>MyApp Distribution Profile 14</string> <!-- Replace with your Provisioning Profile Name -->
               </dict>
           </dict>
           </plist>
@@ -512,64 +512,64 @@ jobs:
       
           echo "app_id=$app_id" >> $GITHUB_ENV
 
-      - name: Get App Store Version ID
-        id: get_app_store_version_id
-        run: |
-          response=$(curl -X GET \
-            -H "Authorization: Bearer ${{ env.token }}" \
-            "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
+      # - name: Get App Store Version ID
+      #   id: get_app_store_version_id
+      #   run: |
+      #     response=$(curl -X GET \
+      #       -H "Authorization: Bearer ${{ env.token }}" \
+      #       "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
       
-          echo "Response: $response"
+      #     echo "Response: $response"
       
-          app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
+      #     app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
       
-          if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
-            echo "Failed to retrieve app store version ID."
-            exit 1
-          fi
+      #     if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
+      #       echo "Failed to retrieve app store version ID."
+      #       exit 1
+      #     fi
       
-          echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
+      #     echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
 
-      - name: Get App Store Version Localization ID
-        id: get_app_store_version_localization_id
-        run: |
-          response=$(curl -X GET \
-            -H "Authorization: Bearer ${{ env.token }}" \
-            "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
+      # - name: Get App Store Version Localization ID
+      #   id: get_app_store_version_localization_id
+      #   run: |
+      #     response=$(curl -X GET \
+      #       -H "Authorization: Bearer ${{ env.token }}" \
+      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
       
-          echo "Response: $response"
+      #     echo "Response: $response"
       
-          app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
+      #     app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
       
-          if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
-            echo "Failed to retrieve app store version localization ID."
-            exit 1
-          fi
+      #     if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
+      #       echo "Failed to retrieve app store version localization ID."
+      #       exit 1
+      #     fi
       
-          echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
+      #     echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
 
-      - name: Update App Store Version Localization
-        id: update_app_store_version_localization
-        run: |
-          response=$(curl -X PATCH \
-            -H "Authorization: Bearer ${{ env.token }}" \
-            -H "Content-Type: application/json" \
-            -d '{
-              "data": {
-                "id": "'${{ env.app_store_version_localization_id }}'",
-                "type": "appStoreVersionLocalizations",
-                "attributes": {
-                  "description": "here goes your app description...",
-                  "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
-                  "marketingUrl": null,
-                  "promotionalText": "We introduce new features and improvements to improve your experience",
-                  "supportUrl": "https://easy-health.app/landing-page/index.html"
-                }
-              }
-            }' \
-            "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
+      # - name: Update App Store Version Localization
+      #   id: update_app_store_version_localization
+      #   run: |
+      #     response=$(curl -X PATCH \
+      #       -H "Authorization: Bearer ${{ env.token }}" \
+      #       -H "Content-Type: application/json" \
+      #       -d '{
+      #         "data": {
+      #           "id": "'${{ env.app_store_version_localization_id }}'",
+      #           "type": "appStoreVersionLocalizations",
+      #           "attributes": {
+      #             "description": "here goes your app description...",
+      #             "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
+      #             "marketingUrl": null,
+      #             "promotionalText": "We introduce new features and improvements to improve your experience",
+      #             "supportUrl": "https://easy-health.app/landing-page/index.html"
+      #           }
+      #         }
+      #       }' \
+      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
           
-          echo "Update App Store Version Localization Response: $response"
+      #     echo "Update App Store Version Localization Response: $response"
 
 
        # ******************************************* Uploading Meta Data END **************************************
@@ -624,7 +624,7 @@ jobs:
             -configuration Release \
             -derivedDataPath ios/build/DerivedData \
             -archivePath ios/build/archive/TestingArchive.xcarchive \
-            PROVISIONING_PROFILE_SPECIFIER="MyApp Distribution Profile 13" \
+            PROVISIONING_PROFILE_SPECIFIER="MyApp Distribution Profile 14" \
             CODE_SIGN_IDENTITY="${CERTIFICATE_NAME}"
             DEVELOPMENT_TEAM="${{ env.TEAM_ID }}"
 
