Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,7 +2,7 @@ name: iOS Certificate Automation
 on:
   push:
     branches:
-      - development
+      - FixesForiOSBuild
 
 jobs:
   build:
@@ -30,16 +30,16 @@ jobs:
         id: extract-variables
         run: |
           BUNDLE_IDentifier=$(grep -E '^  BUNDLE_ID:' ${{ github.workspace }}/config.js | awk -F '[:,]' '{print $2}' | tr -d '[:space:]' | tr -d \')
-          ISSUER_ID=$(grep 'ISSUER_ID=' ${{ github.workspace }}/config.js | awk -F '=' '{print $2}' | tr -d '[:space:]' | tr -d \' | tr -d ',')
-          KEY_ID=$(grep 'KEY_ID=' ${{ github.workspace }}/config.js | awk -F '=' '{print $2}' | tr -d '[:space:]' | tr -d \' | tr -d ',')
+          ISSUER_ID=$(grep -E '^  ISSUER_ID:' ${{ github.workspace }}/config.js | awk -F '[:,]' '{print $2}' | tr -d '[:space:]' | tr -d \')
+          KEY_ID=$(grep -E '^  KEY_ID:' ${{ github.workspace }}/config.js | awk -F '[:,]' '{print $2}' | tr -d '[:space:]' | tr -d \')
       
           # Handle the private key separately and save it to a file
-          awk '/^  private_key="/,/^  "/' ${{ github.workspace }}/config.js | sed -e 's/private_key="//' -e 's/^  //' -e 's/"$//' -e 's/^ *//g' -e '/^$/d' > private_key.pem
+          awk '/^  private_key:/,/^  "/' ${{ github.workspace }}/config.js | sed -e 's/private_key://g' -e 's/^ *//g' -e '/^$/d' > private_key.pem
       
           echo "BUNDLE_IDentifier=$BUNDLE_IDentifier" >> $GITHUB_ENV
           echo "ISSUER_ID=$ISSUER_ID" >> $GITHUB_ENV
           echo "KEY_ID=$KEY_ID" >> $GITHUB_ENV
-          echo "PRIVATE_KEY_PATH=$PWD/private_key.pem" >> $GITHUB_ENV    
+          echo "PRIVATE_KEY_PATH=$PWD/private_key.pem" >> $GITHUB_ENV 
 
       - name: Echo extracted variables
         run: |
@@ -492,84 +492,84 @@ jobs:
 
       # ******************************************* Uploading Meta Data **************************************
 
-      # - name: Get App ID
-      #   id: get_app_id
-      #   run: |
-      #     bundle_id=${{ env.BUNDLE_IDentifier }}  # Replace with your app's Bundle ID
+      - name: Get App ID
+        id: get_app_id
+        run: |
+          bundle_id=${{ env.BUNDLE_IDentifier }}  # Replace with your app's Bundle ID
       
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/apps?filter%5BbundleId%5D=$bundle_id")
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps?filter%5BbundleId%5D=$bundle_id")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_id=$(echo $response | jq -r '.data[0].id')
+          app_id=$(echo $response | jq -r '.data[0].id')
       
-      #     if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
-      #       echo "Failed to retrieve app ID."
-      #       exit 1
-      #     fi
+          if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
+            echo "Failed to retrieve app ID."
+            exit 1
+          fi
       
-      #     echo "app_id=$app_id" >> $GITHUB_ENV
+          echo "app_id=$app_id" >> $GITHUB_ENV
 
-      # - name: Get App Store Version ID
-      #   id: get_app_store_version_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
+      - name: Get App Store Version ID
+        id: get_app_store_version_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
+          app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
       
-      #     if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
-      #       echo "Failed to retrieve app store version ID."
-      #       exit 1
-      #     fi
+          if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
+            echo "Failed to retrieve app store version ID."
+            exit 1
+          fi
       
-      #     echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
+          echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
 
-      # - name: Get App Store Version Localization ID
-      #   id: get_app_store_version_localization_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
+      - name: Get App Store Version Localization ID
+        id: get_app_store_version_localization_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
+          app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
       
-      #     if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
-      #       echo "Failed to retrieve app store version localization ID."
-      #       exit 1
-      #     fi
+          if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
+            echo "Failed to retrieve app store version localization ID."
+            exit 1
+          fi
       
-      #     echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
+          echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
 
-      # - name: Update App Store Version Localization
-      #   id: update_app_store_version_localization
-      #   run: |
-      #     response=$(curl -X PATCH \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       -H "Content-Type: application/json" \
-      #       -d '{
-      #         "data": {
-      #           "id": "'${{ env.app_store_version_localization_id }}'",
-      #           "type": "appStoreVersionLocalizations",
-      #           "attributes": {
-      #             "description": "here goes your app description...",
-      #             "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
-      #             "marketingUrl": null,
-      #             "promotionalText": "We introduce new features and improvements to improve your experience",
-      #             "supportUrl": "https://easy-health.app/landing-page/index.html"
-      #           }
-      #         }
-      #       }' \
-      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
+      - name: Update App Store Version Localization
+        id: update_app_store_version_localization
+        run: |
+          response=$(curl -X PATCH \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            -H "Content-Type: application/json" \
+            -d '{
+              "data": {
+                "id": "'${{ env.app_store_version_localization_id }}'",
+                "type": "appStoreVersionLocalizations",
+                "attributes": {
+                  "description": "here goes your app description...",
+                  "keywords": "medicine reminder, lembrete de medicamentos, easy patient, easy health, gestão da saúde",
+                  "marketingUrl": null,
+                  "promotionalText": "We introduce new features and improvements to improve your experience",
+                  "supportUrl": "https://easy-health.app/landing-page/index.html"
+                }
+              }
+            }' \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersionLocalizations/${{ env.app_store_version_localization_id }}")
           
-      #     echo "Update App Store Version Localization Response: $response"
+          echo "Update App Store Version Localization Response: $response"
 
 
        # ******************************************* Uploading Meta Data END **************************************
@@ -641,90 +641,4 @@ jobs:
       #     path: ios/build/archive/TestingIPA/*.ipa
 
 
-      # - name: Update App Metadata
-      #   run: |
-      #     python <<EOF
-      #     import os
-      #     import requests
-          
-      #     app_id = "36FLSCQT6V"  # The ID of the app you want to update
-      #     token = os.getenv('token')  # Your JWT token for authorization
-      
-      #     # Define the metadata you want to update
-      #     metadata = {
-      #         "data": {
-      #             "type": "apps",
-      #             "id": app_id,
-      #             "attributes": {
-      #                 "name": "Health App",
-      #                 "subtitle": "New Subtitle",
-      #                 "description": "Updated app description.",
-      #                 "keywords": "keyword1, keyword2",
-      #                 "supportUrl": "https://support.example.com",
-      #                 "marketingUrl": "https://marketing.example.com",
-      #                 "privacyPolicyUrl": "https://privacy.example.com",
-      #                 "primaryCategory": "6021",  # Example category ID for "Business"
-      #                 "secondaryCategory": "6011",  # Example category ID for "Productivity"
-      #                 "ageRating": "12+"  
-      #             }
-      #         }
-      #     }
-      
-      #     url = f"https://api.appstoreconnect.apple.com/v1/apps/{app_id}"
-      #     headers = {
-      #         "Authorization": f"Bearer {token}",
-      #         "Content-Type": "application/json"
-      #     }
-      
-      #     response = requests.patch(url, json=metadata, headers=headers)
-      
-      #     if response.status_code == 200:
-      #         print("App metadata updated successfully")
-      #     else:
-      #         print("Failed to update app metadata")
-      #         print(response.status_code)
-      #         print(response.json())
-      #         exit(1)
-      #     EOF
-
-            # - name: Revoke the hardcoded certificate
-      #   run: |
-      #     import requests
-      #     import os
-
-      #     # Hardcoded JWT and Certificate ID
-       
-      #     certificate_id = "LDXBV2688Z"
-
-      #     # API URL
-      #     url = f"https://api.appstoreconnect.apple.com/v1/certificates/{certificate_id}"
-      #     headers = {
-      #         "Authorization": f"Bearer {os.getenv('token')}",
-      #     }
-          
-      #     # Making the DELETE request to revoke the certificate
-      #     response = requests.delete(url, headers=headers)
-          
-      #     # Print the status and response content
-      #     print(f"Status Code: {response.status_code}")
-      #     if response.status_code == 204:
-      #         print("Certificate revoked successfully.")
-      #     else:
-      #         print("Failed to revoke certificate.")
-      #         print(response.text)
-      #   shell: python
-
-            # - name: Retrieve All App IDs
-      #   run: |
-      #     echo "Retrieving App IDs..."
-      #     response=$(curl -s -X GET https://api.appstoreconnect.apple.com/v1/bundleIds \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       -H "Content-Type: application/json")
-          
-      #     echo "$response" > bundle_ids.json
-      #     echo "Bundle IDs Response: $response"
-
-      #     # # Extract and print App IDs
-      #     # bundle_ids=$(jq -r '.data[].id' bundle_ids.json)
-      #     # echo "App IDs: $bundle_ids"
-      #     # echo "bundle_ids=$bundle_ids" >> $GITHUB_ENV
+     
