Update ScreenshotiOS.yml

diff --git a/.github/workflows/ScreenshotiOS.yml b/.github/workflows/ScreenshotiOS.yml
--- a/.github/workflows/ScreenshotiOS.yml
+++ b/.github/workflows/ScreenshotiOS.yml
@@ -273,118 +273,118 @@ jobs:
       # ********************************************************************* Prerequisetires Start *******************************************************************
 
 
-      # - name: Set up Ruby
-      #   uses: ruby/setup-ruby@v1
-      #   with:
-      #     ruby-version: 3.3
+      - name: Set up Ruby
+        uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 3.3
 
-      # - name: Install dependencies
-      #   run: |
-      #     gem install jwt
-      #     pip install requests
+      - name: Install dependencies
+        run: |
+          gem install jwt
+          pip install requests
 
-      # - name: Download private key
-      #   run: |
-      #     curl -o ${{ github.workspace }}/private_key.p8 $private_key
-      #     echo "Downloaded private key."   
+      - name: Download private key
+        run: |
+          curl -o ${{ github.workspace }}/private_key.p8 $private_key
+          echo "Downloaded private key."   
 
-      # - name: Print private key
-      #   run: |
-      #     echo "Private key content:"
-      #     cat ${{ github.workspace }}/private_key.p8
+      - name: Print private key
+        run: |
+          echo "Private key content:"
+          cat ${{ github.workspace }}/private_key.p8
 
 
-      # - name: Generate JWT
-      #   id: generate_jwt
-      #   run: |
-      #     ISSUER_ID=${{ env.ISSUER_ID }}
-      #     KEY_ID=${{ env.KEY_ID }}
+      - name: Generate JWT
+        id: generate_jwt
+        run: |
+          ISSUER_ID=${{ env.ISSUER_ID }}
+          KEY_ID=${{ env.KEY_ID }}
           
-      #     # Load the private key content from the file
-      #     private_key=$(cat "${{ github.workspace }}/private_key.p8")
+          # Load the private key content from the file
+          private_key=$(cat "${{ github.workspace }}/private_key.p8")
       
-      #     # Ensure the private key is correctly formatted
-      #     token=$(ruby -rjwt -ropenssl -e "
-      #       require 'openssl'
-      #       require 'jwt'
+          # Ensure the private key is correctly formatted
+          token=$(ruby -rjwt -ropenssl -e "
+            require 'openssl'
+            require 'jwt'
             
-      #       private_key_obj = OpenSSL::PKey::EC.new('$private_key')
+            private_key_obj = OpenSSL::PKey::EC.new('$private_key')
             
-      #       token = JWT.encode(
-      #         {
-      #           iss: '$ISSUER_ID',
-      #           exp: Time.now.to_i + 20 * 60,
-      #           aud: 'appstoreconnect-v1'
-      #         },
-      #         private_key_obj,
-      #         'ES256',
-      #         header_fields = {
-      #           kid: '$KEY_ID'
-      #         }
-      #       )
-      #       puts token
-      #     ")
+            token = JWT.encode(
+              {
+                iss: '$ISSUER_ID',
+                exp: Time.now.to_i + 20 * 60,
+                aud: 'appstoreconnect-v1'
+              },
+              private_key_obj,
+              'ES256',
+              header_fields = {
+                kid: '$KEY_ID'
+              }
+            )
+            puts token
+          ")
       
-      #     # Save the generated token in the GitHub Actions environment for later steps
-      #     echo "token=$token" >> $GITHUB_ENV
+          # Save the generated token in the GitHub Actions environment for later steps
+          echo "token=$token" >> $GITHUB_ENV
 
 
-      # - name: Get App ID
-      #   id: get_app_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/apps")
+      - name: Get App ID
+        id: get_app_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps")
       
-      #     echo "Full API Response: $response"
+          echo "Full API Response: $response"
       
-      #     app_id=$(echo $response | jq -r '.data[] | select(.attributes.bundleId=="'${{ env.BUNDLE_IDentifier }}'") | .id')
+          app_id=$(echo $response | jq -r '.data[] | select(.attributes.bundleId=="'${{ env.BUNDLE_IDentifier }}'") | .id')
       
-      #     if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
-      #       echo "Failed to retrieve app ID."
-      #       exit 1
-      #     else
-      #       echo "App ID: $app_id"
-      #     fi
+          if [ "$app_id" == "null" ] || [ -z "$app_id" ]; then
+            echo "Failed to retrieve app ID."
+            exit 1
+          else
+            echo "App ID: $app_id"
+          fi
 
       
-      #     echo "app_id=$app_id" >> $GITHUB_ENV
+          echo "app_id=$app_id" >> $GITHUB_ENV
 
-      # - name: Get App Store Version ID
-      #   id: get_app_store_version_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
+      - name: Get App Store Version ID
+        id: get_app_store_version_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/apps/${{ env.app_id }}/appStoreVersions")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
+          app_store_version_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first version
       
-      #     if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
-      #       echo "Failed to retrieve app store version ID."
-      #       exit 1
-      #     fi
+          if [ "$app_store_version_id" == "null" ] || [ -z "$app_store_version_id" ]; then
+            echo "Failed to retrieve app store version ID."
+            exit 1
+          fi
       
-      #     echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
+          echo "app_store_version_id=$app_store_version_id" >> $GITHUB_ENV
 
-      # - name: Get App Store Version Localization ID
-      #   id: get_app_store_version_localization_id
-      #   run: |
-      #     response=$(curl -X GET \
-      #       -H "Authorization: Bearer ${{ env.token }}" \
-      #       "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
+      - name: Get App Store Version Localization ID
+        id: get_app_store_version_localization_id
+        run: |
+          response=$(curl -X GET \
+            -H "Authorization: Bearer ${{ env.token }}" \
+            "https://api.appstoreconnect.apple.com/v1/appStoreVersions/${{ env.app_store_version_id }}/appStoreVersionLocalizations")
       
-      #     echo "Response: $response"
+          echo "Response: $response"
       
-      #     app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
+          app_store_version_localization_id=$(echo $response | jq -r '.data[0].id')  # Assuming you want the first localization
       
-      #     if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
-      #       echo "Failed to retrieve app store version localization ID."
-      #       exit 1
-      #     fi
+          if [ "$app_store_version_localization_id" == "null" ] || [ -z "$app_store_version_localization_id" ]; then
+            echo "Failed to retrieve app store version localization ID."
+            exit 1
+          fi
       
-      #     echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
+          echo "app_store_version_localization_id=$app_store_version_localization_id" >> $GITHUB_ENV
 
 
       #     # ************************************************* Prerequisetires end ***********************************************
